version: '3.7'

services:
  web:
    platform: linux/amd64
    build: .
    image: transcribe    
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app/app
      - ./instance:/app/instance
      - ./data:/app/data
